---
# tasks file for MyWebservers
  
- name: "installing webserver software"
  package:
   name: "httpd"
   state: present

 
- name: "installing php software"
  package:
   name: "php"
   state: present 

- name: "copying the web pages"
  copy:
   src: "index.php"
   dest: "/var/www/html/index.php"

- name: "starting webserver servive"
  service:
   name: "httpd"
   state: restarted
